import { CANONICAL_ROUTES } from "@/constants/canonical-routes";

export const ROUTES = {
  home: CANONICAL_ROUTES.home,
  registration: CANONICAL_ROUTES.registration,
  registrationSuccess: "/registration/success",
  admin: "/admin",
  adminRegistration: (id: string) => `/admin/registrations/${id}`,
  contact: CANONICAL_ROUTES.contact,
  introduction: CANONICAL_ROUTES.introduction,
  academicCouncil: CANONICAL_ROUTES.departments.academicCouncil,
  upcomingEvents: CANONICAL_ROUTES.upcomingEvents,
  pastEvents: CANONICAL_ROUTES.pastEvents,
  committees: CANONICAL_ROUTES.committees,
  mediaCenter: CANONICAL_ROUTES.mediaCenter,
  bestWishes: CANONICAL_ROUTES.bestWishes,
  wishesReceived: CANONICAL_ROUTES.wishesReceived,
  press: CANONICAL_ROUTES.press,
  merchandise: CANONICAL_ROUTES.merchandise,
  privacy: "/privacy-policy",
  terms: "/terms-and-conditions",
  disclaimer: "/disclaimer",
  refund: "/refund-policy",
} as const;

/** Routes that expose PII exports — require admin session cookie */
export const PROTECTED_DATA_ROUTE_PREFIXES = [
  "/admin",
  "/AllData",
  "/participantregistrationdatadekh",
  "/volunteerdatadekh",
  "/volunteerregistrationdatadekh",
  "/ngoregistrationdatadekh",
  "/abstractdatadekh",
  "/fulllengthdatadekh",
  "/fulllengthpaperdatadekh",
  "/organiserdatadekh",
  "/schooldata",
  "/Talentdata",
  "/Conclavedata",
  "/Bestpracticedata",
  "/accomodationdata",
  "/DelegateForm",
  "/heiprojectregistrationdata",
] as const;
