// components/committeeData.ts
export const committeeData = {
    ShikshaKumbh2023: [{
      LocalAdvisoryCommittee: [
        { id: 1, name: "Mr. Vijay Nadda", designation: "Org. Secretary, Vidya Bharti (NZ)" },
        { id: 2, name: "Mr. Balkishan", designation: "Jt. Org. Secretary, Vidya Bharti (NZ)" },
        { id: 3, name: "Mr. Desh Raj", designation: "Gen. Secretary, Vidya Bharti (NZ)" },
        { id: 4, name: "Mr. Praveen Saini", designation: "Vice President, Vidya Bharti (NZ)" },
        { id: 5, name: "Dr. Devprasad Bhardwaj", designation: "President, Vidya Bharti, Haryana" },
        { id: 6, name: "Mr. Manoj Singhal", designation: "Scientific Advisor, DHE" },
        { id: 7, name: "Dr. Amit Kansal", designation: "Independent Director, NHPC" },
        { id: 8, name: "Dr. Avadhesh Pandey", designation: "Gen. Secretary, Hindu Shiksha Samiti, Haryana" },
        { id: 9, name: "Dr. Rishiraj Vashishtha", designation: "President, Hindu Shiksha Samiti, Haryana" }
      ],
      
      OrganizingCommittee: [
        { id: 1, name: "Dr. Pankaj Kumar", designation: "CU, Himachal Pradesh" },
        { id: 2, name: "Mr. Saurabh Sharma", designation: "Dy. Registrar, IK GPTU, Kapurthala" },
        { id: 3, name: "Adv. Poonam Thakur", designation: "Legal Advisor, DHE" },
        { id: 4, name: "Dr. Pratibha Gupta", designation: "President, DHE" },
        { id: 5, name: "Dr. Kuldeep Kumar", designation: "NIT Kurukshetra" },
        { id: 6, name: "Dr. Yogesh Aggarwal", designation: "NIT Kurukshetra" },
        { id: 7, name: "Dr. Tejinder Sharma", designation: "Kurukshetra University" },
        { id: 8, name: "Dr. Avnish Verma", designation: "GJU, Hisar" },
        { id: 9, name: "Dr. Vikas Garg", designation: "Central University Haryana" },
        { id: 10, name: "Dr. Anju Garg", designation: "JC Bose University of Science and Technology" },
        { id: 11, name: "Dr. R. S. Rathore", designation: "Skill University, Gurugram" },
        { id: 12, name: "Dr. Surender Dahiya", designation: "DCRUST, Murthal, Sonepat" },
        { id: 13, name: "Dr. Pankaj Sharma", designation: "Convenor, Alumni Council, Vidya Bharati" },
        { id: 14, name: "Col. K. K. Kakkar", designation: "Retd. Indian Army Officer" }
      ],
      
      ConferenceSecretaries: [
        { id: 1, name: "Prof. Sathans", designation: "NIT Kurukshetra" },
        { id: 2, name: "Mr. Chandra Has Gupta", designation: "Manager, DHE" }
      ],
      
      ConferenceJointSecretaries: [
        { id: 1, name: "Mr. Sanjay Choudhary", designation: "Prachar Pramukh, VBUK" },
        { id: 2, name: "Dr. Gaurav Saini", designation: "NIT Kurukshetra" },
        { id: 3, name: "Dr. Y. Dwivedi", designation: "NIT Kurukshetra" },
        { id: 4, name: "Dr. Neeru", designation: "Joint Director, Skill Development Department, Haryana" }
      ],
      
      ConferenceConveners: [
        { id: 1, name: "Dr. MPR Prasad", designation: "NIT Kurukshetra" },
        { id: 2, name: "Dr. VG Durgarao Rayudu", designation: "NIT Kurukshetra" },
        { id: 3, name: "Dr. Vikram Singh", designation: "NIT Kurukshetra" },
        { id: 4, name: "Mr. Mandeep Tiwari", designation: "Business Advisor, DHE" }
      ],
      
      NationalAdvisoryCommittee: [
        { id: 1, name: "Mr. A Rajarajan", designation: "Director, Satish Dhawan Space Centre" },
        { id: 2, name: "Prof. Anantha Ramakrishnan", designation: "Director, CSIO" },
        { id: 3, name: "Prof. Rajeev Ahuja", designation: "Director, IIT Ropar" },
        { id: 4, name: "Prof. Bhola Ram Gurjar", designation: "Director, NITTR Chandigarh" },
        { id: 5, name: "Prof. R. P. Tiwari", designation: "Vice-Chancellor, CU Punjab" },
        { id: 6, name: "Dr. Kumar Gaurav", designation: "Dy. Director, PGI" },
        { id: 7, name: "Prof. Arvind", designation: "Vice-Chancellor, Punjabi University" },
        { id: 8, name: "Prof. Adarsh Pal Vij", designation: "Chairman, Punjab Pollution Control Board" },
        { id: 9, name: "Prof. Harinder Kumar Chaudhary", designation: "Vice-Chancellor, HAU" },
        { id: 10, name: "Prof. S. K. Mehta", designation: "Vice-Chancellor, UOL" },
        { id: 11, name: "Prof. C. C. Tripathi", designation: "Director, NITTTER Bhopal" },
        { id: 12, name: "Prof. Anupam Shukla", designation: "Director, NIT Surat" },
        { id: 13, name: "Prof. N. N. Pandey", designation: "Vice-Chancellor, MGP Rohilkhand University" },
        { id: 14, name: "Prof. Lalit Kumar Avasthi", designation: "Director, NIT Uttarakhand" },
        { id: 15, name: "Prof. Pawan Kumar Singh", designation: "Director, IIM Trichy" },
        { id: 16, name: "Prof. Rama Shanker Verma", designation: "Director, MNNIT Allahabad" },
        { id: 17, name: "Prof. M. S. Padvi", designation: "Vice-Chancellor, Birsa Munda Tribal University" },
        { id: 18, name: "Prof. K.N. Natwarsinh Chawda", designation: "Vice-Chancellor, VNSGU" },
        { id: 19, name: "Prof. Raj Nath Yadava", designation: "Vice-Chancellor, Purnea University" },
        { id: 20, name: "Prof. Amar P. Garg", designation: "Vice-Chancellor, Shobhit University" },
        { id: 21, name: "Dr. G.C. Bhimani", designation: "Vice-Chancellor, Saurashtra University, Rajkot" },
        { id: 22, name: "Dr. Rajnish Arora", designation: "Ex-VC, I.K. Gujral Punjab Technical University" },
        { id: 23, name: "Prof. Binod Kumar Kanaujia", designation: "Director, NIT Jalandhar" },
        { id: 24, name: "Mr. Kashmiri Lal", designation: "Org. Secretary, Swadeshi Jagran Manch" },
        { id: 25, name: "Mr. Raghunandan", designation: "Org. Secretary, VB- Ucch Shiksha Sansthan" },
        { id: 26, name: "Mr. Satish Kumar", designation: "Joint Org. Secretary, Swadeshi Jagran Manch" },
        { id: 27, name: "Dr. Jaideep Arya", designation: "Chairman, Yog Aayog, Haryana" },
        { id: 28, name: "Mr. Prateek Kishore", designation: "Director, TBRL/DRDO" },
        { id: 29, name: "Prof. Vidyadhar Subudhi", designation: "Director, NIT Warangal" },
        { id: 30, name: "Prof. H. M. Suryawanshi", designation: "Director, NIT Hamirpur" },
        { id: 31, name: "Prof. O. R. Jaiswal", designation: "Director, NIT Goa" },
        { id: 32, name: "Prof. K K Shukla", designation: "Director, IIT Bhilai" }
      ]}
    ],
    ShikshaKumbh2024: [{
      LocalAdvisoryCommittee: [
        { id: 1, name: "Mr. Vijay Nadda", affiliation: "Vidya Bharti (NZ)" },
        { id: 2, name: "Mr. Balkishan", affiliation: "Vidya Bharti (NZ)" },
        { id: 3, name: "Mr. Desh Raj", affiliation: "Vidya Bharti (NZ)" },
        { id: 4, name: "Mr. Parveen Saini, IAS (Retd.)", affiliation: "Vidya Bharti (NZ)" },
        { id: 5, name: "Mr. Manoj Singhal", affiliation: "DHE" },
        { id: 6, name: "Dr. Amit Kansal", affiliation: "NHPC" },
        { id: 7, name: "Er. Ved Bhushan Sharma", affiliation: "BSS, J&K" },
        { id: 8, name: "Er. Hari Bhushan", affiliation: "BSS, J&K" },
        { id: 9, name: "Dr. Manoj", affiliation: "BSS, J&K" },
        { id: 10, name: "Dr. Amit Kumar", affiliation: "SKUAST, Kashmir" },
        { id: 11, name: "Prof. M. K. Sharma", affiliation: "SKUAST, Kashmir" },
        { id: 12, name: "Prof. Aijaz Ahmad", affiliation: "University of Kashmir" },
        { id: 13, name: "Prof. Kartar Chand Sharma", affiliation: "Kashmir University" },
        { id: 14, name: "Dr. Omchand Sharma", affiliation: "CITH Srinagar" },
        { id: 15, name: "Dr. Yogesh Pandey", affiliation: "SKAUST Kashmir" },
        { id: 16, name: "Dr. Sunil Kumar", affiliation: "SKAUST Kashmir" },
        { id: 17, name: "Dr. Manoj Kumar", affiliation: "CITH Srinagar" },
        { id: 18, name: "Maj. Gen. Suresh Kumar Khajuria (Retd.)", affiliation: "SES, Punjab" }
      ],
      OrganizingCommittee: [
        { id: 1, name: "Dr. Yashwant Mehta", affiliation: "NIT Srinagar" },
        { id: 2, name: "Dr. H. S. Pali", affiliation: "NIT Srinagar" },
        { id: 3, name: "Dr. Jitendra Gurjar", affiliation: "NIT Srinagar" },
        { id: 4, name: "Dr. R. P. Shukla", affiliation: "NIT Srinagar" },
        { id: 5, name: "Dr. Pankaj Kumar", affiliation: "CU, Himachal Pradesh" },
        { id: 6, name: "Mr. Saurabh Sharma", affiliation: "IKGPTU, Kapurthala" },
        { id: 7, name: "Adv. Poonam Thakur", affiliation: "DHE, Mohali" },
        { id: 8, name: "Dr. Pratibha Gupta", affiliation: "DHE, Mohali" },
        { id: 9, name: "Col. K. K. Kakkar", affiliation: "DHE, Mohali" },
        { id: 10, name: "Dr. Gurmeet Singh", affiliation: "University of Kashmir" },
        { id: 11, name: "Dr. Praveen Sharma", affiliation: "University of Kashmir" },
        { id: 12, name: "Dr. Bhawani Singh", affiliation: "University of Jammu" },
        { id: 13, name: "Mr. Mandeep Tiwari", affiliation: "DHE, Mohali" },
        { id: 14, name: "Dr. Ramjit", affiliation: "CU, Kashmir" }
      ],
      ConferenceSecretaries: [
        { id: 1, name: "Prof. Manjit Bansal", affiliation: "MRS PTU" },
        { id: 2, name: "Prof. Yashwant Mehta", affiliation: "NIT Srinagar" },
        { id: 3, name: "Dr. Saad Parvez", affiliation: "IIEDC, NIT Srinagar" }
      ],
      ConferenceJointSecretaries: [
        { id: 1, name: "Dr. Praveen Kumar Sharma", affiliation: "CU, Jammu" },
        { id: 2, name: "Dr. Vijay Kumar", affiliation: "NIT Srinagar" },
        { id: 3, name: "Dr. Ranjeet Kumar Rout", affiliation: "NIT Srinagar" },
        { id: 4, name: "Dr. Naresh Kumar", affiliation: "CU, Jammu" }
      ],
      ConferenceConveners: [
        { id: 1, name: "Dr. Harveer Singh Pali", affiliation: "NIT Srinagar" },
        { id: 2, name: "Dr. Neeraj Gupta", affiliation: "NIT Srinagar" },
        { id: 3, name: "Mr. Shahid Abbas Mir", affiliation: "NIT Srinagar" }
      ],
      NationalAdvisoryCommittee: [
        { id: 1, name: "Prof. Nilofer Khan", affiliation: "Vice-Chancellor, University of Kashmir" },
        { id: 2, name: "Prof. Nazir Ah. Ganai", affiliation: "Vice-Chancellor, SKUAST Srinagar" },
        { id: 3, name: "Prof. A. Ravinder Nath", affiliation: "Vice Chancellor, Central University, Kashmir" },
        { id: 4, name: "Prof. Qayyum Hussain", affiliation: "Vice Chancellor, Cluster University Kashmir" },
        { id: 5, name: "Prof. Sanjeev Jain", affiliation: "Vice-Chancellor, Central University, Jammu" },
        { id: 6, name: "Prof. B.S. Sahay", affiliation: "Director, IIM Jammu" },
        { id: 7, name: "Dr. Manoj Singh Gaur", affiliation: "Director, IIT Jammu" },
        { id: 8, name: "Dr. Shakti Kumar Gupta", affiliation: "Director, AIIMS Jammu" },
        { id: 9, name: "Prof. Bechan Lal", affiliation: "Vice-Chancellor, Cluster University Jammu" },
        { id: 10, name: "Prof. Pragati Kumar", affiliation: "Vice-Chancellor, SMVDU" },
        { id: 11, name: "Prof. Akbar Masood", affiliation: "Vice-Chancellor, BGSBU" },
        { id: 12, name: "Dr. B.N. Tripathi", affiliation: "Vice-Chancellor, SKUAST, Jammu" },
        { id: 13, name: "Prof. Umesh Rai", affiliation: "Vice-Chancellor, University of Jammu" },
        { id: 14, name: "Lt. Gen. Dr. Anup Banerji", affiliation: "Director, AIIMS Kashmir" },
        { id: 15, name: "Prof. S. K. Mehta", affiliation: "Vice-Chancellor, University of Ladakh" },
        { id: 16, name: "Mr. A Rajarajan", affiliation: "Director, Satish Dhawan Space Centre" },
        { id: 17, name: "Prof. Shantanu Bhattacharya", affiliation: "Director, CSIO" },
        { id: 18, name: "Prof. Rajeev Ahuja", affiliation: "Director, IIT Ropar" },
        { id: 19, name: "Prof. Bhola Ram Gurjar", affiliation: "Director, NITTTR Chandigarh" },
        { id: 20, name: "Prof. R. P. Tiwari", affiliation: "Vice-Chancellor, CU Punjab" },
        { id: 21, name: "Dr. Kumar Gaurav", affiliation: "Dy. Director, PGI" },
        { id: 22, name: "Prof. Arvind", affiliation: "Vice-Chancellor, Punjabi University" },
        { id: 23, name: "Prof. Adarsh Pal Vij", affiliation: "Chairman, Punjab Pollution Control Board" },
        { id: 24, name: "Prof. B. R. Kamboj", affiliation: "Vice-Chancellor, HAU" },
        { id: 25, name: "Prof. S. K. Mehta", affiliation: "Vice-Chancellor, UOL" },
        { id: 26, name: "Prof. C. C. Tripathi", affiliation: "Director, NITTTR Bhopal" },
        { id: 27, name: "Prof. Anupam Shukla", affiliation: "Director, NIT Surat" },
        { id: 28, name: "Prof. K. P. Singh", affiliation: "Vice-Chancellor, MJP Rohilkhand University" },
        { id: 29, name: "Dr. Madhu Chitkara", affiliation: "Vice-Chancellor, Chitkara University" },
        { id: 30, name: "Mr. Ajay Gupta", affiliation: "CEO, SATYA Group" }
      ]
    }
    ],
    Shikshamahakumbh2023: [{
      LocalAdvisoryCommittee: [
        { id: 1, name: "Mr. Vijay Kumar Nadda", designation: "Organisational Secretary, Vidya Bharti (North Region)" },
        { id: 2, name: "Mr. Balkishan", designation: "Jt. Organisational Secretary, Vidya Bharti (North Region)" },
        { id: 3, name: "Mr. Rajendra Kumar", designation: "Organisational Secretary, Vidya Bharti (Punjab)" },
        { id: 4, name: "Dr. S. K. Mishra", designation: "Registrar, I.K. Gujral PTU, Kapurthala" },
        { id: 5, name: "Mr. Praveen Saini", designation: "IAS (Retd.), Vice President, Vidya Bharti (North Region)" },
        { id: 6, name: "Major General Suresh Khajuria (Retd.)", designation: "President, Sarvhitkari Educational Society" },
        { id: 7, name: "Mr. Subhas Mahajan", designation: "Vice President, Sarvhitkari Educational Society" },
        { id: 8, name: "Prof. Navdeep Shekhar", designation: "General Secretary, Sarvhitkari Educational Society" },
        { id: 9, name: "Mr. Manoj Singhal", designation: "Scientific Advisor, Department of Holistic Education" },
      ],
    
      OrganizingCommittee: [
        { id: 1, name: "Mr. P.S. Khimita", designation: "SVM Malerkotla" },
        { id: 2, name: "Dr. Gagandeep Parashar", designation: "SVM Bhikhi" },
        { id: 3, name: "Dr. Jagdeep Patial", designation: "SVM Mansa" },
        { id: 4, name: "Mrs. Jyoti Sharma", designation: "SVM" },
        { id: 5, name: "Dr. Akhileshwar", designation: "SVM Jalandhar" },
        { id: 6, name: "Mr. Vikram Sanyal", designation: "SVM" },
        { id: 7, name: "Dr. Shashikant Yadav", designation: "NIT Jalandhar" },
        { id: 8, name: "Dr. Pankaj Kumar", designation: "CU, Himachal Pradesh" },
        { id: 9, name: "Mr. Saurabh Sharma", designation: "Dy. Registrar, IK Gujral PTU, Kapurthala" },
        { id: 10, name: "Ms. Kavita Sharma", designation: "IT Advisor, Department of Holistic Education, SES" },
        { id: 11, name: "Mr. Rajeev Sharma", designation: "Founder Member, Health Quest Foundation" },
        { id: 12, name: "Adv. Poonam Thakur", designation: "Legal Advisor, Department of Holistic Education, SES" },
        { id: 13, name: "Dr. Ashok Bagga", designation: "NIT Jalandhar" },
        { id: 14, name: "Dr. Ghanshyam Neje", designation: "NIT Jalandhar" },
        { id: 15, name: "Dr. Pratibha Gupta", designation: "Academic Advisor, Department of Holistic Education, SES" },
      ],
    
      OrganizingSecretaries: [
        { id: 1, name: "Mr. Chandra Has Gupta", designation: "Secretary, SES" },
        { id: 2, name: "Prof. Anish Sachdeva", designation: "NIT Jalandhar" },
        { id: 3, name: "Dr. Shailendra Bajpai", designation: "NIT Jalandhar" },
      ],
    
      ConferenceJointSecretaries: [
        { id: 1, name: "Mr. Vijay Thakur", designation: "Finance Secretary, SES" },
        { id: 2, name: "Dr. Kapil Kumar Goyal", designation: "NIT Jalandhar" },
        { id: 3, name: "Dr. Karanveer", designation: "NIT Jalandhar" },
      ],
    
      ConferenceConveners: [
        { id: 1, name: "Dr. Mohit Tyagi", designation: "NIT Kurukshetra" },
        { id: 2, name: "Dr. Deepika Rani", designation: "NIT Jalandhar" },
        { id: 3, name: "Dr. Samayveer Singh", designation: "NIT Jalandhar" },
      ],
    
      ConferenceCoordinators: [
        { id: 1, name: "Shri Sanyog Dutt" },
        { id: 2, name: "Dr. Neeraj Pant", designation: "Co-ordinator, Western Uttar Pradesh Zone" },
        { id: 3, name: "Smt Neetu Khurana", designation: "Co-ordinator, North Zone" },
        { id: 4, name: "Shri Dayanidhi", designation: "Co-ordinator, Central Zone" },
        { id: 5, name: "Dr. Hital Patel", designation: "Co-ordinator, West Zone" },
        { id: 6, name: "Dr. Amitesh Kumar", designation: "Co-ordinator, Bihar Zone" },
      ],
    
      NationalAdvisoryCommittee: [
        { id: 1, name: "Mr. A Rajarajan", designation: "Director, Satish Dhawan Space Centre" },
        { id: 2, name: "Prof. Anantha Ramakrishnan", designation: "Director, CSIO" },
        { id: 3, name: "Prof. Rajeev Ahuja", designation: "Director, IIT Ropar" },
        { id: 4, name: "Prof. Gowari Shankar", designation: "Director, IISER Mohali" },
        { id: 5, name: "Prof. Shyam Sundar Pattnaik", designation: "Director, NITTR Chandigarh" },
        { id: 6, name: "Prof. R. P. Tiwari", designation: "Vice-Chancellor, CU Punjab" },
        { id: 7, name: "Dr. Kumar Gaurav", designation: "Dy. Director, PGI" },
        { id: 8, name: "Dr. S. C. Ralhan", designation: "Chairman, BOG of NIT Jalandhar" },
        { id: 9, name: "Prof. Arvind", designation: "Vice-Chancellor, Punjabi University" },
        { id: 10, name: "Dr. Rajiv Prasad", designation: "Secretary, Higher Secondary Education, Haryana" },
        { id: 11, name: "Prof. Adarsh Pal Vij", designation: "Chairman, Punjab Pollution Control Board" },
        { id: 12, name: "Prof. Rajendrakumar Anayath", designation: "Vice Chancellor, DCR University of Science and Technology, Sonepat" },
        { id: 13, name: "Prof. Yogesh Singh", designation: "Vice Chancellor, DU" },
        { id: 14, name: "Prof. Harinder Kumar Chaudhary", designation: "Vice Chancellor, HAU" },
        { id: 15, name: "Prof. S. K. Mehta", designation: "Vice Chancellor, UOL" },
        { id: 16, name: "Prof. C. C. Tripathi", designation: "Director, NITTTER Bhopal" },
        { id: 17, name: "Prof. Anupam Shukla", designation: "Director, NIT Surat" },
        { id: 18, name: "Prof. N. N. Pandey", designation: "Vice Chancellor, MGP Rohilkhand University, Bareilly" },
        { id: 19, name: "Prof. B. V. R. Reddy", designation: "Director, NIT Kurukshetra" },
        { id: 20, name: "Mr. Vikash Trikha", designation: "Director, SCL" },
        { id: 21, name: "Secretary", designation: "Higher Secondary Education, Punjab" },
        { id: 22, name: "Secretary", designation: "Higher Secondary Education, Haryana" },
        { id: 23, name: "Secretary", designation: "Higher Secondary Education, Himachal" },
        { id: 24, name: "Secretary", designation: "Higher Secondary Education, Delhi" },
        { id: 25, name: "Secretary", designation: "Higher Secondary Education, Jammu and Kashmir" },
        { id: 26, name: "Director", designation: "IIT Delhi" },
        { id: 27, name: "Director", designation: "IIT Mandi" },
        { id: 28, name: "Director", designation: "NIT Hamirpur" },
        { id: 29, name: "Dr. Rakesh Sehgal", designation: "Director, NIT Srinagar" },
        { id: 30, name: "Director", designation: "NIT Kurukshetra" },
        { id: 31, name: "Director", designation: "IIIT Una" },
      ]
    }
  ],
    ShikshaMahaKumbh2024: {
      NationalAdvisoryCommittee: [
        { id: 1, name: "Mr. S. Somanath", designation: "Chairman, ISRO" },
        { id: 2, name: "Mr. A. Rajarajan", designation: "Director, SDSC" },
        { id: 3, name: "Dr. Samir V. Kamat", designation: "Chairman, DRDO" },
        { id: 4, name: "Dr. Ajit Kumar Mohanty", designation: "Chairman, DAE" },
        { id: 5, name: "Prof. Dinesh Prasad Saklani", designation: "Chairman, NCERT" },
        { id: 6, name: "Mrs. Nidhi Chhibber", designation: "Chairperson, CBSE" },
        { id: 7, name: "Prof. Yogesh Singh", designation: "Chairperson, NCTE" },
        { id: 8, name: "Dr. Nirmaljeet Singh Kalsi", designation: "Chairperson, NCVET" },
        { id: 9, name: "Mr. Mamidala Jagadesh Kumar", designation: "Chairperson, UGC" },
        { id: 10, name: "Prof. Rajive Kumar", designation: "Member Secretary, AICTE" },
        { id: 11, name: "Mr. Govindan Rangarajan", designation: "Director, IISc" },
        { id: 12, name: "Prof. Anantha Ramakrishnan", designation: "Director, CSIO" },
        { id: 13, name: "Prof. Adarsh Pal Vij", designation: "Chairman, PPCB" },
        { id: 14, name: "Dr. Jaideep Arya", designation: "Chairman, Yog Aayog, Haryana" },
        { id: 15, name: "Mr. Prateek Kishore", designation: "Director, TBRL/DRDO" },
        { id: 16, name: "Mr. Kashmiri Lal", designation: "Org. Secretary, SJM" },
        { id: 17, name: "Mr. Raghunandan", designation: "Org. Secretary, VB - USS" },
        { id: 18, name: "Mr. Satish Kumar", designation: "Joint Org. Secretary, SJM" },
        { id: 19, name: "Prof. Pawan Kumar Singh", designation: "Director, IIM Trichy" },
        { id: 20, name: "Prof. Laxmidhar Behera", designation: "Director, IIT Mandi" },
        { id: 21, name: "Prof. Manoj Singh Gaur", designation: "Director, IIT Jammu" },
        { id: 22, name: "Prof. Shreepad Karmakar", designation: "Director, IIT Bhubaneswar" },
        { id: 23, name: "Prof. V. R. Desai", designation: "Director, IIT Dharwad" },
        { id: 24, name: "Prof. Binod Kumar Kanaujia", designation: "Director, NIT Jalandhar" },
        { id: 25, name: "Prof. B.V. Ramana Reddy", designation: "Director, NIT Kurukshetra" },
        { id: 26, name: "Prof. O. R. Jaiswal", designation: "Director, NIT Goa" },
        { id: 27, name: "Prof. Anupam Shukla", designation: "Director, NIT Surat" },
        { id: 28, name: "Prof. Lalit Kumar Avasthi", designation: "Director, NIT Uttarakhand" },
        { id: 29, name: "Prof. M. C. Govil", designation: "Director, NIT Sikkim" },
        { id: 30, name: "Prof. Gautam Sutradhar", designation: "Director, NIT Jamshedpur" },
        { id: 31, name: "Prof. Ajay Sharma", designation: "Director, NIT Delhi" },
        { id: 32, name: "Prof. Venu Gopal", designation: "Director, NIT Nagaland" },
        { id: 33, name: "Prof. Ramana Rao", designation: "Director, NIT Raipur" },
        { id: 34, name: "Prof. Prasad Krishna", designation: "Director, NIT Calicut" },
        { id: 35, name: "Prof. K. K. Shukla", designation: "Director, MANIT Bhopal" },
        { id: 36, name: "Prof. N. P. Padhy", designation: "Director, MNIT Jaipur" },
        { id: 37, name: "Prof. Usha", designation: "Director, NITTTR Chennai" },
      ],
      
      LocalAdvisoryCommittee: [
        { id: 1, name: "Mr. Vijay Nadda", designation: "Org. Secretary, Vidya Bharti (NZ)" },
        { id: 2, name: "Mr. Balkishan", designation: "Jt. Org. Secretary, Vidya Bharti (NZ)" },
        { id: 3, name: "Dr. Ashok Pal", designation: "President, Vidya Bharti (NZ)" },
        { id: 4, name: "Mr. Surendar Attri", designation: "Vice President, Vidya Bharti (NZ)" },
        { id: 5, name: "Mr. Praveen Saini", designation: "Vice President, Vidya Bharti (NZ)" },
        { id: 6, name: "Mr. Desh Raj", designation: "Gen. Secretary, Vidya Bharti (NZ)" },
        { id: 7, name: "Dr. Manoj Kumar Teotia", designation: "CRRID, Chandigarh" },
        { id: 8, name: "Dr. Pooja D.", designation: "CSIR-CSIO, Chandigarh" },
        { id: 9, name: "Dr. Praveen Kumar", designation: "IACS, Kolkata" },
        { id: 10, name: "Dr. Jitesh Kumar Pandey", designation: "PMIDC, DLG, Punjab" },
        { id: 11, name: "Mr. Manoj Singhal", designation: "Scientific Advisor, DHE" },
      ],
    
      OrganizingCommittee: [
        { id: 1, name: "Dr. Pankaj Kumar", designation: "CU, Himachal Pradesh" },
        { id: 2, name: "Mr. Saurabh Sharma", designation: "Dy. Registrar, IKGPTU, Amritsar Campus" },
        { id: 3, name: "Dr. Pratibha Gupta", designation: "President, DHE" },
        { id: 4, name: "Dr. Amit Kansal", designation: "Independent Director, NHPC" },
        { id: 5, name: "Dr. Ravi Kant", designation: "IIT Ropar" },
        { id: 6, name: "Dr. Kishant Kumar", designation: "IIT Ropar" },
        { id: 7, name: "Dr. Tharamani C.N.", designation: "IIT Ropar" },
        { id: 8, name: "Prof. Sathans", designation: "NIT Kurukshetra" },
        { id: 9, name: "Dr. Vijay Kumar Sharma", designation: "NIT Srinagar" },
        { id: 10, name: "Dr. Vipan Pal Singh", designation: "CU, Punjab" },
        { id: 11, name: "Dr. Anshul", designation: "Delhi University" },
        { id: 12, name: "Dr. Nitya Sharma", designation: "IKGPTU" },
        { id: 13, name: "Dr. Neelum", designation: "LPU" },
        { id: 14, name: "Mr. Saurabh Sharma", designation: "IKGPTU" },
        { id: 15, name: "Prof. Anish Sachdeva", designation: "NIT Jalandhar" },
        { id: 16, name: "Dr. Praveen Sharma", designation: "CU, Jammu" },
        { id: 17, name: "Dr. Ravi Prakash", designation: "CBLU, Haryana" },
        { id: 18, name: "Dr. Shamsher Singh", designation: "AB College Pathankot" },
        { id: 19, name: "Dr. Ankit", designation: "LLRUVAS, Hisar, Haryana" },
      ],
    
      ConferenceDirector: [
        { id: 1, name: "Dr. Thakur SKR", designation: "Sci/Engr-SF, ISRO and Director, DHE & VBITR" },
      ],
    
      ConferenceSecretaries: [
        { id: 1, name: "Dr. Pushpendra P. Singh", designation: "Dy. Registrar, IIT Ropar" },
        { id: 2, name: "Dr. H. V. Vasudevan", designation: "Dy. Director, DHE" },
      ],
    
      ConferenceTreasurers: [
        { id: 1, name: "Dr. Gajendra Rana", designation: "Assistant Registrar, DHE" },
        { id: 2, name: "Mr. Bhupender", designation: "Accountant, DHE" },
      ],
    
      StudentCommittee: [
        { id: 1, name: "Ankush Verma", designation: "IIT Ropar" },
        { id: 2, name: "Aman Kumar", designation: "IIT Ropar" },
        { id: 3, name: "Shashank", designation: "IIT Ropar" },
        { id: 4, name: "Akash Goyal", designation: "IIT Ropar" },
        { id: 5, name: "Harvinder Singh", designation: "IIT Ropar" },
        { id: 6, name: "Manjeet Singh", designation: "IIT Ropar" },
        { id: 7, name: "Gurpreet Singh", designation: "IIT Ropar" },
        { id: 8, name: "Ashok Kumar", designation: "IIT Ropar" },
      ],
   
      // Add more members...
  },
    // Add more committees as needed...
};
  